In [8]:
import pandas as pd
from dataclasses import asdict
from src import data_utils as d
from src import file_utils as f
from src.params import filepaths
from src.constants import CharacteristicsOriginalColumns, CCIS_COLUMN_RENAME

from glob import glob
import os
import uuid
from collections import defaultdict

In [3]:
df = d.load_csv("../data/raw/ccis_original_csv/ccis_original_mar22.csv", read_as_str=True)

Reading ../data/raw/ccis_original_csv/ccis_original_mar22.csv
Reading all data as str

In [6]:
df.columns

Index(['DatabaseId', 'LEACode', 'DateOfSend', 'PeriodEnd', 'SupplierName',
       'SupplierXMLVersion', 'XMLSchemaVersion', 'YoungPersonsID',
       'CohortStatus', 'GivenName', 'MiddleName', 'FamilyName', 'AddressLine1',
       'AddressLine2', 'AddressLine3', 'AddressLine4', 'Town', 'County',
       'Postcode', 'Gender', 'moth/year of birth', 'Ethnicity', 'LeadLEA',
       'EducatedLEA', 'UniqueLearnerNo', 'UniquePupilNumber',
       'PreviousYPIDIdentifier', 'GuaranteeStatusIndicator', 'LEACodeAtYear11',
       'TransferredToLACode', 'LevelOfNeedCode', 'SENDFlag', 'SENSupportFlag',
       'CharacteristicCode', 'ActivityCode', 'StartDate', 'DateAscertained',
       'DateVerified', 'DueToLapseDate', 'CurrencyLapsed',
       'EstablishmentNumber', 'EstablishmentName', 'UKProviderReferenceNumber',
       'PredictedEndDate', 'ReviewDate', 'NEETStartDate',
       'IntendedDestinationYr11'],
      dtype='object')

In [11]:
reverse_rename = {v: k for k, v in CCIS_COLUMN_RENAME.items() if v in asdict(CharacteristicsOriginalColumns).values()}
reverse_rename[CharacteristicsOriginalColumns.level_of_need_code] = "LevelOfNeedCode"
reverse_rename.pop(CharacteristicsOriginalColumns.date_of_birth)

'DOB'

In [12]:
df[reverse_rename.values()]

,AddressLine1,AddressLine2,AddressLine3,AddressLine4,CharacteristicCode,County,EstablishmentNumber,Ethnicity,FamilyName,Gender,GivenName,LevelOfNeedCode,MiddleName,Postcode,SENDFlag,SENSupportFlag,Town,UniquePupilNumber,moth/year of birth
0,,,,,,,794200615,WBRI,,F,,3,,,Y,Y,,6584a44d-3aef-464f-b646-b4cf960b1a10,07/2005
1,,,,,,,906412125,NOBT,,W,,3,,,N,N,,143d2975-238a-4687-b541-85ec4930fc6b,02/2005
2,,,,,,,440395066,BAFR,,M,,3,,,N,N,,f84cdf94-ff3d-4b8f-ae14-46992bfd8b03,03/2004
3,,,,,,,647516298,AIND,,M,,3,,,N,Y,,,10/2005
4,,,,,,,599529752,WOTH,,M,,3,,,N,Y,,3e9787e4-d0c2-41c6-9cd7-e1f7ae919f4b,02/2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,,,,,,,847020528,WBRI,,F,,3,,,N,N,,5d0380b2-8cef-4964-a841-1b109400c6ba,08/2006
9996,,,,,,,621086815,WBRI,,M,,3,,,N,Y,,fca17970-a81b-4dd2-8638-fde38ac99151,02/2004
9997,,,,,,,713423851,WBRI,,M,,3,,,N,N,,bb345f1c-9943-4f94-8a72-34f5eecbc597,06/2006
9998,,,,,,,501023248,WBRI,,F,,3,,,N,Y,,8423de4a-d7c1-49ad-a162-0d30b18a524b,04/2005
9999,,,,,,,834403213,AOTH,,F,,3,,,N,N,,68d23e5d-19e4-410e-95ae-0910368396e8,12/2004